[remote]
# Server address. No ability for custom TCP ports atm, in close TODO
url = "http://example.com"      

# A custom root path on remote web server, for example "/eset_upd", will result in this url: "https://example.com/eset_upd"
root_path = "/"           

# User credentials (if they are used). Not working atm, in close TODO
username = ""
password = ""

# Custom user-agent. HWF is not real, randomized, but should work. 
user_agent = "EEA Update (Windows; U; 64bit; BPC 11.0.2044.0; OS: 10.0.26100 SP 0.0 NT; HWF: 010036A1-5CFB-7212-B781-C437D9015CAD; PLOC ru_ru; PCODE 107.0.0; PAR -1; ATH -1; DC 0; PLID 3AC-9SP-9D9; SEAT 154b3474; RET 2107)"

# Excluded architectures (can be "x64", "x86" and "arm64" values). 
# If empty [], all architectures will be downloaded.
# Example below:  filter = ["x86", "arm64"] <- this will downloads only "x64"
filter = ["x86", "arm64"]

[local]
# Directory for downloaded files on your machine. Can be relative or absolute.
root_path = "/web/public_html"
